// Generated by CoffeeScript 1.6.3
(function() {
  jQuery(function() {
    var buttonSize, commandsHeight, commandsWidth, containerHeight, iframe;
    containerHeight = $('.container').css;
    ({
      'height': function() {
        return $(window).height() * 0.9;
      }
    });
    commandsHeight = $('.Q, .W, .E, .A, .S, .D').css;
    ({
      'height': function() {
        return $('#commands').height() * 0.4;
      }
    });
    commandsWidth = $('#commands').css;
    ({
      'width': function() {
        return $('.container').width() * 0.6;
      }
    });
    buttonSize = $('#commands').css;
    ({
      'height': function() {
        return $('.container').height() * 0.2;
      }
    });
    iframe = $('iframe').css;
    ({
      'height': function() {
        return $('.container').height() * 0.6;
      }
    });
    return $(window).resize(function() {
      return containerHeight();
    });
  });

}).call(this);
