// Generated by CoffeeScript 1.6.3
(function() {
  $(document.ready(function() {
    $(document.keydown = function(e) {
      var adress, key;
      adress = "http://192.168.0.105:8071/motion-control/update";
      key = e.which;
      if (key === 81) {
        $(".Q").addClass('active');
        $.ajax({
          url: adress,
          data: {
            strafe: 1
          },
          dataType: "jsonp"
        });
      }
      if (key === 87) {
        $(".W").addClass('active');
        $.ajax({
          url: adress,
          data: {
            forward: 1
          },
          dataType: "jsonp"
        });
      }
      if (key === 69) {
        $(".E").addClass('active');
        $.ajax({
          url: adress,
          data: {
            strafe: -1
          },
          dataType: "jsonp"
        });
      }
      if (key === 65) {
        $(".A").addClass('active');
        $.ajax({
          url: adress,
          data: {
            turn: -1
          },
          dataType: "jsonp"
        });
      }
      if (key === 83) {
        $(".S").addClass('active');
        $.ajax({
          url: adress,
          data: {
            forward: -1
          },
          dataType: "jsonp"
        });
      }
      if (key === 68) {
        $(".D").addClass('active');
        return $.ajax({
          url: adress,
          data: {
            turn: 1
          },
          dataType: "jsonp"
        });
      }
    });
    return $(document.keyup = function(e) {
      $(".Q,.S,.D,.A,.E,.W").removeClass('active');
      return $.ajax({
        url: adress,
        data: {
          forward: 0
        },
        dataType: "jsonp"
      });
    });
  }));

}).call(this);
